In [1]:
import numpy as np
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
import tensorflow as tf
import time
from binaryflow import deploy

In [2]:
n=11272
u=np.random.choice([-1,1],[n,128])
A=np.random.choice([-1,1],[512,n])

In [5]:
%timeit A@u

3.35 s ± 32 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
A_B=deploy.binarize(A)

In [5]:
%timeit deploy.binarized_batch_mat_mul(A_B,u)

95.3 ms ± 1.75 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [6]:
%timeit A@u

3.14 s ± 87 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
A_gpu=tf.constant(A)
u_gpu=tf.constant(u)
%timeit A_gpu@u_gpu

2022-09-05 16:20:26.029210: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-09-05 16:20:26.029416: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: fedora
2022-09-05 16:20:26.029451: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: fedora
2022-09-05 16:20:26.029818: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 515.65.1
2022-09-05 16:20:26.029920: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 515.65.1
2022-09-05 16:20:26.029949: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 515.65.1
2022-09-05 16:20:26.031315: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in perf

41.2 ms ± 2.02 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [15]:
def F():
    with tf.device("/cpu:0"):
        return A_gpu@u_gpu
%timeit F()

25 ms ± 65.7 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
def do_nothing(u):
    s,r=binarize(u,retPaddingCount=True)
    print(r)
    return unbinarize(s,r<<3)
(u==do_nothing(u)).all()

4


True

In [563]:
len(float)

TypeError: object of type 'type' has no len()

In [331]:
binarize(u).shape

(300, 311)

In [183]:
(unbinarize(A_B) != A).sum()

0

In [18]:
(A.astype(np.int8)@u.astype(np.float16))

array([[  66.,    6.,  -16., ...,  204.,   46., -124.],
       [-138.,   90.,  208., ..., -204.,  -54., -376.],
       [  12.,  -68.,  110., ..., -134.,  260., -190.],
       ...,
       [  72., -212.,  -50., ..., -362.,  148., -206.],
       [  48.,  164.,  -42., ...,  146., -220.,  182.],
       [ 138., -150.,  -20., ...,  -72.,   -6., -156.]], dtype=float16)

In [241]:
bit_count(np.array([1,1,1])).sum()<<1

6

In [11]:
BinarizedBatchMatMul(A_B,u)-(A@u).T

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [22]:
tf.bitwise.left_shift(tf.constant([1,2,3]),2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4,  8, 12], dtype=int32)>

In [336]:
1563*64

100032

In [566]:
binarize(np.array([True]))

array([128], dtype=uint64)

In [571]:
np.pad([True],(0,10))

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [578]:
I=np.random.normal(0,1,[28,28,3])

In [585]:
n=3
m=3
i=0
j=0
np.pad(I[max(i-n//2,0):min(i+n//2+1,n-1),max(j-m//2,j+m//2+m-1):min(),...],[(max(0,n//2-i),max(n//2-n+1+i,0)),(max(0,m//2-j),max(m//2-m+1+j,0)),0]).flatten()

TypeError: `pad_width` must be of integral type.

In [582]:
[0,(max(0,n//2-i),max(n//2-n+1+i,0)),(max(0,m//2-j),max(m//2-m+1+j,0)),0]

[0, (1, 0), (1, 0), 0]

In [588]:
I[max(i-n//2,0):min(i+n//2+1,n-1),max(j-m//2,j+m//2+m-1),...].shape

(2, 3)

In [12]:
np.float32

numpy.float32

In [37]:
C=tf.constant([1,6,3,2])

In [31]:
tf.concat([c for c in C],axis=0)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 6, 3, 2], dtype=int32)>

In [32]:
(C==1)pit

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True, False, False, False])>

In [35]:
tf.compat.v2.raw_ops.Compare

<module 'tensorflow.compat.v1.raw_ops' from '/home/ramizouari/anaconda3/envs/tensorflow_2_9/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v1/raw_ops/__init__.py'>

In [80]:
%timeit binarize_tensor(A)

26.5 ms ± 1.51 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [79]:
%timeit binarize((A))

26.4 ms ± 1.44 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [54]:
C.dtype

tf.int32

In [71]:
C.dtype.size

4

In [85]:
tf.cast(C,float)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 6., 3., 2.], dtype=float32)>

In [116]:
%timeit binarized_batch_mat_mul_tensor(binarize_tensor(A),u)

219 ms ± 3.12 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [117]:
%timeit BinarizedBatchMatMul(A_B,u)

367 ms ± 23.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [120]:
tf.transpose(np.array([[1,2],[3,1]]))

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[1, 3],
       [2, 1]])>

In [5]:
from tensorflow import raw_ops
raw_ops.CompareAndBitpack

AttributeError: module 'tensorflow._api.v2.raw_ops' has no attribute 'CompareAndBitpack'

In [11]:
import tensorflow.compat.v1.raw_ops
tf.compat.v1.raw_ops.bitpa

<module 'tensorflow.compat.v1.raw_ops' from '/home/ramizouari/anaconda3/envs/tensorflow_2_9/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v1/raw_ops/__init__.py'>